### ISSUE TITLE
ResourceExhaustedError when running the file evaluate_sample.py with my own video

### ISSUE THREAD

**Issue by mourad1081** [deepmind/kinetics-i3d#74]
Hello, I am trying to run the file `evaluate_sample.py` with my own video as input. **It works well with the given cricket sample video**, but it simply does not work with mine.

The only difference between the sample video and mine is their duration. Mine has 987 frames while the cricket one is 79 frames long. Thus, the `myvideo_rgb.npy` file weights 1.2 Go and the `myvideo_flow.npy` weights 791 Mo.

I do not understand how can I have such an error since my video is not very heavy (1 minute and 32s)... and I have some videos that are way longer than that (1 hour long)...

My configuration :
- GPU: Nvidia GTX 1080 (8 GB)
- Tensorflow-gpu

I also tried to set the tensorflow session's config like below but it did not solve anything : 
```
config = tf.ConfigProto()
config.gpu_options.allocator_type = 'BFC'
config.gpu_options.per_process_gpu_memory_fraction = 0.40
with tf.Session(config=config) as sess:
```

My final goal is to be able to extract features of my videos.

**Comment by joaoluiscarreira** [comment]
Hi,

that is natural. You'll just have to pass a smaller chunk of frames to the
model each time, then combine the results. I don't know what's the maximum
number of frames that saturates the GPU memory, you'll have to try a few
values -- e.g. 256 frames.

Joao

**Comment by mourad1081** [comment]
Thank you, I'll try that after some researches. 

> then combine the results
The average of the output results?

Also, I just noticed that python does not allocate more than 4GB of my GPU's memory. Maybe that's because I run the code on Ubuntu 14?

**Comment by mourad1081** [comment]
It works now. I input chunks of 512 frames to the network, haven't tried more.
